#!/usr/bin/env python
# -*- coding: utf-8 -*-
# EASY-INSTALL-ENTRY-SCRIPT: 'box-training-methods','console_scripts','box_training_methods'
__requires__ = "box-training-methods"
import re
import sys

from box_training_methods.__main__ import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
